
jobs:
  build:
    machine:
      image: 'ubuntu-1604:201903-01'
    steps:
      - checkout
      - matlab/install
      - matlab/run-command:
          command:  main_ci

workflows:
  version: 2
  workflow:
    jobs:
      - build:
          filters:
            branches:
              only: master

orbs:
  matlab: mathworks/matlab@0.3.0

version: 2.1
