
jobs:
  build:
    machine:
      image: 'ubuntu-1604:201903-01'
    steps:
      - checkout
      - matlab/install
      - matlab/run-command:
          command:  main_ci

workflows:
  version: 2
  workflow:
    triggers:
      - schedule:
          filters:
            branches:
              only:
                - master
    jobs:
      - build

orbs:
  matlab: mathworks/matlab@0.3.0

version: 2.1
